name: Deploy to EC2 on Push

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -e # Stop script on error
          cd ~/question-craft-export
          echo "Pulling latest code..."
          git pull origin main
          echo "Installing pnpm if not present..."
          if ! command -v pnpm &> /dev/null; then
           curl -fsSL https://get.pnpm.io/install.sh | sh -
           export PNPM_HOME="$HOME/.local/share/pnpm"
           export PATH="$PNPM_HOME:$PATH"
           echo 'export PNPM_HOME="$HOME/.local/share/pnpm"' >> ~/.bashrc
           echo 'export PATH="$PNPM_HOME:$PATH"' >> ~/.bashrc
          else
           echo "pnpm already installed"
          fi
          export PNPM_HOME="$HOME/.local/share/pnpm"
          export PATH="$PNPM_HOME:$PATH"
          echo "Installing dependencies..."
          pnpm install
          echo "Building frontend..."
          pnpm run build
          echo "Restarting backend..."
          pm2 restart backend || pm2 start backend.js --name backend
